### ISSUE TITLE
the  Scalar of GENERATOR, 

### ISSUE THREAD

**Issue by simplelins** [dusk-network/bls12_381#100]
in my mind, the scalar is in montgomery form. such as  the ROOT_OF_UNITY Scalar([
    0xb9b58d8c5f0e466a,
    0x5b1b4c801819d7ec,
    0x0af53ae352a31e64,
    0x5bf3adda19e9b27b,
])   that is in montgomery form.

but why the GENERATOR is  Scalar([7, 0, 0, 0]), it is in normal  form.

**Comment by simplelins** [comment]
> Related to [dusk-network/piecrust#118](https://github.com/dusk-network/piecrust/issues/118) ?

oh， no， the  GENERATOR use to cosetfft and coset_ifft, the result is different from other libs for the value of GENERATOR .

**Comment by moCello** [comment]
You are absolutely right, we missed a `from_raw` in this. Luckily we don't seem to use this constant anywhere, so I removed it entirely. Thanks a lot for pointing this out!

**Comment by simplelins** [comment]
ok, thanks for your work
