### ISSUE TITLE
Random API

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/bls12_381#14]
We are lacking an API to generate random scalars.

I would recommend the implementation of `Distribution` with `Standard`, as in
https://github.com/dusk-network/phoenix/blob/master/src/transaction/mod.rs#L189

This interops very well with foreign types

**Comment by CPerezz** [comment]
Well, meanwhile it's true, you can basically generate a random array of 32 bytes and build a `Scalar` from them.

But ye, it will be a good think to add, I agree.

**Comment by CPerezz** [comment]
#15 adds support for random `Scalar` generation.

I'm not 100% sure that we need to follow the Uniform distribution logic "per-se".
For now probably the implementation we have is enough. But we can maybe think of it when we have a bit more time.
