### ISSUE TITLE
Implement is_zero & is_one fn for `Scalar`

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/bls12_381#20]
>I'm wondering, if we have `Scalar::one()` and `Scalar::zero` as shortcut, and we do a lot of >comparison with both (at least `Scalar::zero`), maybe we should add a utility method such as >`.is_zero` ? So we would have `if !u.is_zero() {` and `let y = if u.is_zero() {`.
>
>What do you think?

_Originally posted by @ZER0 in https://github.com/dusk-network/dusk-blindbid/pull/10_

**Comment by ZER0** [comment]
For my understanding we have to possible way to approach the API:

**1. A single `is_zero()` / `is_one()` method that returns a `Choice`**
_Pro_: Can be easily used together with the rest of `subtle`, such as `ConditionallySelectable` trait.
_Cons_: For `boolean` check `into()` must be used (e.g. `let y = if u.is_zero().into() {`)

**2. Implements methods for both `boolean` and `Choice`: `is_zero()` / `is_one()` and `ct_is_zero()` / `ct_is_one()`**
_Pro_: We can use `ct_is_zero()` when we need to deal with `subtle` and `ConditionallySelectable` and `is_zero` for `boolean` checks.
_Cons_: The API is verbose, two method that virtually are doing the same thing just to save a `.into()` inside an `if` (the `boolean` methods are a wrapper to the `Choice` methods, plus`into()`) and possibly confusing.
