### ISSUE TITLE
Implement Canon for Scalar

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/bls12_381#36]
The serialization of the merkle trees relies on the implementation of `canonical::Canon` and `canonical_derive::Canon` for `Scalar`

**Comment by vlopes11** [comment]
Test with https://github.com/dusk-network/bls12_381/tree/derive_canon

**Comment by CPerezz** [comment]
Was this closed via #37 @vlopes11 ??

**Comment by CPerezz** [comment]
Closed via #37
