### ISSUE TITLE
`to_raw_bytes` for `G1Affine`

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/bls12_381#44]
We need a function that will store the bytes of a `G1Affine` as "raw".

This way, the reconstruction of multiple points can be much faster for trusted sets of data.

Implement the dusk-to_bytes traits

Fixes:
https://github.com/dusk-network/plonk/issues/332

**Comment by autholykos** [comment]
This issue should provide information about blocking tasks.

**Comment by vlopes11** [comment]
Fixed in v0.5.0
