### ISSUE TITLE
Add a `clippy` action to CI and fix warnings

### ISSUE THREAD

**Issue by ZER0** [dusk-network/bls12_381#77]
**Describe what you want implemented** 
Now that Clippy is mature enough, we should have it added on the CI as an action and fix any warning it raises, by addressing the issue when possible, or adding the exception to the rule when it's not.

**Describe "Why" this is needed**
It helps to maintain a certain level of quality in the code, and ensure we all have the same guidelines for some common pattern.
Also, it consistent with other repos in our organization when we're already doing so (see [rusk](https://github.com/dusk-network/rusk/blob/master/.github/workflows/dusk_ci.yml#L52) for example).

**Comment by HDauven** [comment]
After a couple of attempts, I would advice against implementing this change for a number of reasons:
1. Upstream runs on Rust stable 1.56.0, we choose to run on a nightly build. This naturally means we deviate in Clippy rules and run into "compatibility" issues. 
2. To adopt Clippy's suggestions, we require experimental features with regard to non-const function calls in const functions. This would make us divulge from upstream again.
